version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: user_password
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - backend

  # Nuxt.js App
  nuxt:
    build:
      context: ./font-end/example
      dockerfile: Dockerfile
    container_name: nuxt_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./font-end/example:/usr/src/app
    networks:
      - frontend
    depends_on:
      - database

  # Nest.js App
  nest:
    build:
      context: ./back-end/example/
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "7777:7777"
    environment:
      NODE_ENV: development
    volumes:
      - ./back-end/example:/usr/src/main.ts
    networks:
      - backend

volumes:
  db_data:


networks:
  frontend:
  backend:
